apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chart-env-injector.name" . }}-cfg
  labels:
    app.kubernetes.io/name: {{ include "chart-env-injector.name" . }}
    chart: {{ template "chart-env-injector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"
webhooks:
  - name: env-injector.hmcts.net
    clientConfig:
      service:
        name: {{ include "chart-env-injector.name" . }}-svc
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        hmcts.github.com/envInjector: enabled
