apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-env-injector.name" . }}-cleanup-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "chart-env-injector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-delete,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-8"
data:
  config.sh: |
    #!/bin/bash

    kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io {{ include "chart-env-injector.name" . }}-cfg
    kubectl delete secret {{ include "chart-env-injector.name" . }}-certs -n {{ .Release.Namespace }}
