apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart-env-injector.name" . }}-ca-config-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "chart-env-injector.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-2"
spec:
  template:
    metadata:
      name: {{ include "chart-env-injector.name" . }}-ca-config-job-tpl
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ template "chart-env-injector.name" . }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: env-injector
      containers:
        - name: pre-install-job
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c", "/etc/config/config.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "chart-env-injector.name" . }}-ca-config
            defaultMode: 0755
