apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-env-injector.name" . }}-svc
  labels:
    app.kubernetes.io/name: {{ include "chart-env-injector.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "chart-env-injector.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app.kubernetes.io/name: {{ include "chart-env-injector.name" . }}
