apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: rpe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: hmctspublic.azurecr.io/docker-curl
          command: ["sleep","1d"]
          imagePullPolicy: Always
