apiVersion: v1
kind: ConfigMap
metadata:
  name: env-injector-webhook-configmap
data:
  envconfig.yaml: |
    env:
      - name: CLUSTER_NAME
        value: aks-test-01
    dnsOptions:
      - name: ndots
        value: 3
    requiredNodeAffinityTerms:
      - matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: NotIn
            values:
              - system
    preferredNodeAffinityTerms:
      - weight: 1
        preference:
          matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: DoesNotExist
    tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        effect: NoSchedule
        operator: Equal
        value: spot
    topologyConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        nodeAffinityPolicy: Honor
        nodeTaintsPolicy: Honor
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: test-app
        matchLabelKeys:
          - pod-template-hash