apiVersion: v1
kind: ConfigMap
metadata:
  name: env-injector-webhook-configmap
data:
  envconfig.yaml: |
    env:
      - name: INJECTOR_TEST
        value: enabled
    removePodAntiAffinity: true
    requiredNodeAffinityTerms:
      - matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: NotIn
            values:
              - system
    preferredNodeAffinityTerms:
      - weight: 50
        preference:
          matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: In
              values:
                - spot
      - weight: 1
        preference:
          matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: DoesNotExist
    tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        effect: NoSchedule
        operator: Equal
        value: spot
    topologyConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.azure.com/agentpool
        whenUnsatisfiable: DoNotSchedule
        nodeAffinityPolicy: Honor
        nodeTaintsPolicy: Honor
        labelSelector:
          matchLabels:
            app.kubernetes.io/managed-by: Helm
        matchLabelKeys:
          - pod-template-hash
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        nodeAffinityPolicy: Honor
        nodeTaintsPolicy: Honor
        labelSelector:
          matchLabels:
            app.kubernetes.io/managed-by: Helm
        matchLabelKeys:
          - pod-template-hash