apiVersion: v1
kind: ConfigMap
metadata:
  name: env-injector-webhook-configmap
data:
  envconfig.yaml: |
    env:
      - name: CLUSTER_NAME
        value: aks-test-01
    dnsOptions:
      - name: ndots
        value: 3
      - name: single-request-reopen
      - name: use-vc
#    nodeAffinityTerms:
#      - matchExpressions:
#          - key: agentpool
#            operator: In
#            values:
#              - ubuntu18
#              - ubuntu1804