apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: env-injector-webhook-cfg
  labels:
    app: env-injector
webhooks:
  - name: env-injector.hmcts.net
    admissionReviewVersions: [v1beta1, v1]
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: env-injector-webhook-svc
#        namespace: admin
        namespace: env-injector
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGRENDQXZ5Z0F3SUJBZ0lVWXBZSldDK1MwS1MvYnVwM3hNbHZpT3JDQUpVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1N6RVZNQk1HQTFVRUNoTU1aVzUyTFdsdWFtVmpkRzl5TVRJd01BWURWUVFERXlsbGJuWXRhVzVxWldOMApiM0l0ZDJWaWFHOXZheTF6ZG1NdVpXNTJMV2x1YW1WamRHOXlMbk4yWXpBZUZ3MHlOVEV5TVRBeE5UTXlNVGhhCkZ3MHlOakV5TVRBeE5UTXlNVGhhTUVzeEZUQVRCZ05WQkFvVERHVnVkaTFwYm1wbFkzUnZjakV5TURBR0ExVUUKQXhNcFpXNTJMV2x1YW1WamRHOXlMWGRsWW1odmIyc3RjM1pqTG1WdWRpMXBibXBsWTNSdmNpNXpkbU13Z2dFaQpNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURSTkd4MXdOblBreko2TzV6UCtpZlROalc1CmMzWFZ2Z0NGQnpiMEpDSEZja2o2eElmcWoybTR4dkVsMDJ4YVlBbisvdXpZNVdiNjZXWXdNUDl6azVpUnd4RFIKT3FmK0ROeXMvQUhkeWwzS3RhNVltWFAxK0tPM2RLNFRuUnFsdFFQdFZiM0tuaXR3OVQvQnlFT3poL0EyY1JaWgplTG42NkRwVUF2WUVRQ3pYbUJQRnZjUnBadG40bEFEb1VKOXcrd3I2UWgyeTl6OG53MjlRUmwvME1XeE4yY0JFCkxwV2NYcm9NclorMVU3TkZOMWhNTktUajAybXI5YnNlVWNsbmw0dVZ5citqV0c2SzZtbGhmak5oc2YvMmNReUgKTW1uc210akVoSlNWSmFnSjBrZHdMQkg4Z1dCdnQwNm9iVlBNbit6ZTM4SUZnVGZwQ0FxRmRBNlVpQ2dkQWdNQgpBQUdqZ2U4d2dld3dEZ1lEVlIwUEFRSC9CQVFEQWdXZ01Bd0dBMVVkRXdFQi93UUNNQUF3Z2NzR0ExVWRFUVNCCnd6Q0J3SUlsWlc1MkxXbHVhbVZqZEc5eUxYZGxZbWh2YjJzdVpXNTJMV2x1YW1WamRHOXlMbk4yWTRJelpXNTIKTFdsdWFtVmpkRzl5TFhkbFltaHZiMnN1Wlc1MkxXbHVhbVZqZEc5eUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGcwpnaWxsYm5ZdGFXNXFaV04wYjNJdGQyVmlhRzl2YXkxemRtTXVaVzUyTFdsdWFtVmpkRzl5TG5OMlk0STNaVzUyCkxXbHVhbVZqZEc5eUxYZGxZbWh2YjJzdGMzWmpMbVZ1ZGkxcGJtcGxZM1J2Y2k1emRtTXVZMngxYzNSbGNpNXMKYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYUE40K0VERTduK1ZJN3ZrWEVuS09QbGNsTEhxQUt6ZgpFRkE3cWlveXMxTnloTjVubC9LZlRIa2RveHpvNGFLeS9ZOU5XRVEzZGEwaU1MRFpFUmJ5MmROeEhmMGtUYXhHCmZuSkNDMmxSK2JPTXBIOVMzcmhyQTVROFVLOW5Ic0k3c1dUenVrejVQZVF3aWJvektVVnVTR3FidkNnTTlXOEIKenRkWlFObHY3Uy9aVGYvVW5GdTFCbHd4bGlUbE1LWUdOcXdWcFo5a3phckdDYVNjaGFGclJWTWU1cnBPeWcvVgpyV0c2T0t2d0h6TkJhSDl0eEVxek1RckVSNDRxT28vMjRFWHY1cC92MjhqZUY3WFEvY0djenM5NjU1RW1OeC9NCnJURmJCdGZESitTSTI4RDlrTHF1eWNtUGxnK242Y05ESGd1N2tVejlhaytmNEc5K0VuSHJlZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        hmcts.github.com/envInjector: enabled
